# Generated by Django 5.1.4 on 2025-01-31 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DriverData",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "driver_code",
                    models.CharField(max_length=200, null=True, unique=True),
                ),
                ("driver_name", models.TextField(max_length=100, null=True)),
                ("status", models.TextField(max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now=True, null=True)),
                ("created_by", models.CharField(max_length=200, null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("updated_by", models.CharField(max_length=200, null=True)),
            ],
            options={
                "db_table": "tbl_driver_data",
            },
        ),
        migrations.CreateModel(
            name="VehicleData",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("vendor_code", models.TextField(max_length=100, null=True)),
                (
                    "vehicle_code",
                    models.CharField(max_length=200, null=True, unique=True),
                ),
                ("register_no", models.TextField(max_length=200, null=True)),
                ("make", models.TextField(max_length=200, null=True)),
                ("engine_no", models.TextField(max_length=200, null=True)),
                ("chasis_no", models.TextField(max_length=200, null=True)),
                ("color", models.TextField(max_length=200, null=True)),
                ("model", models.TextField(max_length=200, null=True)),
                ("cc", models.TextField(max_length=200, null=True)),
                ("fuel_type", models.TextField(max_length=200, null=True)),
                ("total_mileage", models.FloatField(null=True)),
                ("status", models.TextField(max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now=True, null=True)),
                ("created_by", models.CharField(max_length=200, null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("updated_by", models.CharField(max_length=200, null=True)),
            ],
            options={
                "db_table": "tbl_vehicle_data",
            },
        ),
        migrations.CreateModel(
            name="VehicleDriver",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "veh_dr_code",
                    models.CharField(max_length=200, null=True, unique=True),
                ),
                ("status", models.TextField(max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now=True, null=True)),
                ("created_by", models.CharField(max_length=200, null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("updated_by", models.CharField(max_length=200, null=True)),
                (
                    "driver_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppVehicle.driverdata",
                        to_field="driver_code",
                    ),
                ),
                (
                    "vehicle_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppVehicle.vehicledata",
                        to_field="vehicle_code",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_vehicle_driver",
            },
        ),
    ]
