# Generated by Django 5.1.4 on 2025-02-01 07:01

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppVehicle", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackerRawData",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "gprs_raw_code",
                    models.CharField(max_length=200, null=True, unique=True),
                ),
                ("latitude", models.FloatField(null=True)),
                ("longitude", models.FloatField(null=True)),
                ("rms_error", models.TextField(max_length=200, null=True)),
                ("g_status", models.TextField(max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(max_length=200, null=True)),
                (
                    "vehicle_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppVehicle.vehicledata",
                        to_field="vehicle_code",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_tracker_raw_data",
            },
        ),
        migrations.CreateModel(
            name="TrackerVehicle",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("terminal_no", models.CharField(max_length=200, null=True)),
                ("company_name", models.TextField(max_length=200, null=True)),
                ("status", models.TextField(max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(max_length=200, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.CharField(max_length=200, null=True)),
                (
                    "vehicle_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppVehicle.vehicledata",
                        to_field="vehicle_code",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_tracker_vehicle",
            },
        ),
        migrations.CreateModel(
            name="VehicleLiveMonitor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "veh_live_mont_code",
                    models.CharField(max_length=200, null=True, unique=True),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("latitude", models.FloatField(null=True)),
                ("longitude", models.FloatField(null=True)),
                ("rms_error", models.TextField(max_length=200, null=True)),
                ("g_status", models.TextField(max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(max_length=200, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.CharField(max_length=200, null=True)),
                (
                    "vehicle_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppVehicle.vehicledata",
                        to_field="vehicle_code",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_vehicle_live_monitor",
            },
        ),
    ]
