# Generated by Django 5.1.4 on 2025-02-04 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppVehicle", "0002_trackerrawdata_trackervehicle_vehiclelivemonitor"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackerrawdata",
            name="system_date_Time",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="trackerrawdata",
            name="vendor_date_Time",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
