# Generated by Django 5.1.4 on 2025-02-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppVehicle", "0003_trackerrawdata_system_date_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trackerrawdata",
            name="system_date_Time",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="trackerrawdata",
            name="vendor_date_Time",
            field=models.DateTimeField(blank=True),
        ),
    ]
