# Generated by Django 5.1.4 on 2025-02-04 19:26

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AppVehicle", "0004_alter_trackerrawdata_system_date_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackerrawdata",
            name="geom",
            field=django.contrib.gis.db.models.fields.GeometryField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
