# Generated by Django 5.1.4 on 2025-02-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppVehicle", "0005_trackerrawdata_geom"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackerrawdata",
            name="avg_speed",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="trackerrawdata",
            name="device_status",
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="trackerrawdata",
            name="max_speed",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="trackerrawdata",
            name="speed",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="trackerrawdata",
            name="vehicle_status",
            field=models.TextField(max_length=200, null=True),
        ),
    ]
