# Generated by Django 5.1.4 on 2025-02-25 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AppVehicle", "0006_trackerrawdata_avg_speed_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trackerrawdata",
            old_name="system_date_Time",
            new_name="system_date_time",
        ),
        migrations.RenameField(
            model_name="trackerrawdata",
            old_name="vendor_date_Time",
            new_name="vendor_date_time",
        ),
    ]
