# Generated by Django 5.1.4 on 2025-02-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "AppVehicle",
            "0007_rename_system_date_time_trackerrawdata_system_date_time_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackerSchedule",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("check_in", models.TextField(max_length=200, null=True)),
                ("check_out", models.TextField(max_length=200, null=True)),
                ("time_duration", models.TextField(max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(max_length=200, null=True)),
            ],
            options={
                "db_table": "tbl_tracker_schedule",
            },
        ),
    ]
