# Generated by Django 5.1.4 on 2025-02-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppVehicle", "0008_trackerschedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trackerschedule",
            name="check_in",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="trackerschedule",
            name="check_out",
            field=models.DateTimeField(blank=True),
        ),
    ]
