# Generated by Django 5.1.4 on 2025-02-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppVehicle", "0009_alter_trackerschedule_check_in_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackerschedule",
            name="process_status",
            field=models.TextField(max_length=200, null=True),
        ),
    ]
