# Generated by Django 5.1.4 on 2025-02-26 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppAsset", "0008_assetgeofence_feature_code"),
        ("AppVehicle", "0010_trackerschedule_process_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContainerTrackerGPRS",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(max_length=200, null=True)),
                (
                    "container_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppAsset.containerdata",
                        to_field="container_code",
                    ),
                ),
                (
                    "gprs_raw_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppVehicle.trackerrawdata",
                        to_field="gprs_raw_code",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_container_tracker_gprs",
            },
        ),
    ]
