# Generated by Django 5.1.4 on 2025-03-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppVehicle", "0011_containertrackergprs"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "vehicle_type_code",
                    models.CharField(max_length=200, null=True, unique=True),
                ),
                ("vehicle_type_name", models.TextField(max_length=100, null=True)),
                ("status", models.TextField(max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now=True, null=True)),
                ("created_by", models.CharField(max_length=200, null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("updated_by", models.CharField(max_length=200, null=True)),
            ],
            options={
                "db_table": "tbl_vehicle_type",
            },
        ),
    ]
