# Generated by Django 5.1.4 on 2025-03-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppVehicle", "0012_vehicletype"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicledata",
            name="vehicle_type",
            field=models.TextField(max_length=200, null=True),
        ),
    ]
