# Generated by Django 5.1.4 on 2025-03-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppVehicle", "0013_vehicledata_vehicle_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackerrawdata",
            name="direction",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="trackerrawdata",
            name="distance",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="trackerrawdata",
            name="mileage",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="trackerrawdata",
            name="terminal_no",
            field=models.BigIntegerField(null=True),
        ),
    ]
