# Generated by Django 5.1.7 on 2025-04-22 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "AppVehicle",
            "0014_trackerrawdata_direction_trackerrawdata_distance_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="vehiclelivemonitor",
            name="direction",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="vehiclelivemonitor",
            name="speed",
            field=models.FloatField(null=True),
        ),
    ]
