# Generated by Django 5.1.7 on 2025-04-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppVehicle", "0015_vehiclelivemonitor_direction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehiclelivemonitor",
            name="device_status",
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="vehiclelivemonitor",
            name="duration",
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="vehiclelivemonitor",
            name="geo_location",
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="vehiclelivemonitor",
            name="ignition_status",
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="vehiclelivemonitor",
            name="vendor_date_time",
            field=models.TextField(max_length=200, null=True),
        ),
    ]
