# Generated by Django 5.1.7 on 2025-04-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppVehicle", "0016_vehiclelivemonitor_device_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkScheduleGPRSApi",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=200, null=True, unique=True)),
                ("work_date", models.DateField(blank=True)),
                ("run_count", models.TextField(max_length=200, null=True)),
                ("process_status", models.TextField(max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(max_length=200, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.CharField(max_length=200, null=True)),
            ],
            options={
                "db_table": "tbl_work_schedule_gprs_api",
            },
        ),
    ]
