# Generated by Django 5.1.7 on 2025-04-23 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppVehicle", "0017_workschedulegprsapi"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleScheduleGPRSApi",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "veh_api_code",
                    models.CharField(max_length=200, null=True, unique=True),
                ),
                ("process_done", models.DateTimeField(blank=True)),
                ("retrieve_record", models.IntegerField(null=True)),
                ("vendor_record", models.IntegerField(null=True)),
                ("process_status", models.TextField(max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(max_length=200, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.CharField(max_length=200, null=True)),
                (
                    "vehicle_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppVehicle.vehicledata",
                        to_field="vehicle_code",
                    ),
                ),
                (
                    "wsa_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppVehicle.workschedulegprsapi",
                        to_field="code",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_vehicle_schedule_gprs_api",
            },
        ),
    ]
