# Generated by Django 5.1.7 on 2025-04-25 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppVehicle", "0018_vehicleschedulegprsapi"),
    ]

    operations = [
        migrations.AddField(
            model_name="workschedulegprsapi",
            name="description",
            field=models.TextField(max_length=200, null=True),
        ),
    ]
