# Generated by Django 5.1.7 on 2025-04-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppVehicle", "0019_workschedulegprsapi_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicleschedulegprsapi",
            name="process_done",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
