# Generated by Django 5.1.7 on 2025-04-27 05:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppVehicle", "0020_alter_vehicleschedulegprsapi_process_done"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicleschedulegprsapi",
            name="veh_sch_date",
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
