# Generated by Django 5.1.7 on 2025-04-28 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppVehicle", "0021_vehicleschedulegprsapi_veh_sch_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleTripData",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("vtd_code", models.CharField(max_length=200, null=True, unique=True)),
                ("from_side", models.TextField(max_length=200, null=True)),
                ("to_side", models.TextField(max_length=200, null=True)),
                ("parent_code", models.TextField(max_length=200, null=True)),
                ("description", models.TextField(null=True)),
                ("status", models.TextField(max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now=True, null=True)),
                ("created_by", models.CharField(max_length=200, null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("updated_by", models.CharField(max_length=200, null=True)),
                (
                    "vehicle_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppVehicle.vehicledata",
                        to_field="vehicle_code",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_vehicle_trip_data",
            },
        ),
        migrations.CreateModel(
            name="VehicleTripGPRSData",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("vtgd_code", models.CharField(max_length=200, null=True, unique=True)),
                ("created_at", models.DateTimeField(auto_now=True, null=True)),
                ("created_by", models.CharField(max_length=200, null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("updated_by", models.CharField(max_length=200, null=True)),
                (
                    "gprs_raw_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppVehicle.trackerrawdata",
                        to_field="gprs_raw_code",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_vehicle_trip_gprs_data",
            },
        ),
    ]
