# Generated by Django 5.1.7 on 2025-04-28 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppVehicle", "0022_vehicletripdata_vehicletripgprsdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicletripdata",
            name="from_check_in",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicletripdata",
            name="from_check_out",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicletripdata",
            name="from_time_spent",
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="vehicletripdata",
            name="to_check_in",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicletripdata",
            name="to_check_out",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicletripdata",
            name="to_time_spent",
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="vehicletripgprsdata",
            name="vtd_code",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="AppVehicle.vehicletripdata",
                to_field="vtd_code",
            ),
        ),
    ]
