# Generated by Django 5.1.7 on 2025-04-28 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppVehicle", "0023_vehicletripdata_from_check_in_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeighingTripData",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("wgt_code", models.CharField(max_length=200, null=True, unique=True)),
                ("total_weight", models.FloatField(null=True)),
                ("reference_no", models.FloatField(null=True)),
                (
                    "attachment",
                    models.ImageField(null=True, upload_to="Invoice/WeighingBill"),
                ),
                ("created_at", models.DateTimeField(auto_now=True, null=True)),
                ("created_by", models.CharField(max_length=200, null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("updated_by", models.CharField(max_length=200, null=True)),
                (
                    "vtd_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppVehicle.vehicletripdata",
                        to_field="vtd_code",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_weighing_trip_data",
            },
        ),
    ]
