# Generated by Django 5.1.7 on 2025-04-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppVehicle", "0024_weighingtripdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicledata",
            name="pitb_code",
            field=models.TextField(max_length=100, null=True),
        ),
    ]
