# Generated by Django 5.1.7 on 2025-05-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppVehicle", "0025_vehicledata_pitb_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicletripdata",
            name="trip_code",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
