# Generated by Django 5.1.7 on 2025-05-02 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppVehicle", "0026_vehicletripdata_trip_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleDependentApi",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("wgt_code", models.CharField(max_length=200, null=True, unique=True)),
                ("total_weight", models.FloatField(null=True)),
                ("reference_no", models.FloatField(null=True)),
                (
                    "attachment",
                    models.ImageField(null=True, upload_to="Invoice/WeighingBill"),
                ),
                ("created_at", models.DateTimeField(auto_now=True, null=True)),
                ("created_by", models.CharField(max_length=200, null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("updated_by", models.CharField(max_length=200, null=True)),
                (
                    "vehicle_type_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppVehicle.vehicletype",
                        to_field="vehicle_type_code",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_vehicle_dependent_api",
            },
        ),
    ]
