# Generated by Django 5.1.7 on 2025-05-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppVehicle", "0027_vehicledependentapi"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vehicledependentapi",
            old_name="wgt_code",
            new_name="code",
        ),
        migrations.RemoveField(
            model_name="vehicledependentapi",
            name="attachment",
        ),
        migrations.RemoveField(
            model_name="vehicledependentapi",
            name="reference_no",
        ),
        migrations.RemoveField(
            model_name="vehicledependentapi",
            name="total_weight",
        ),
        migrations.AddField(
            model_name="vehicledependentapi",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="vehicledependentapi",
            name="status",
            field=models.TextField(max_length=200, null=True),
        ),
    ]
