# Generated by Django 5.1.7 on 2025-05-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppVehicle", "0028_rename_wgt_code_vehicledependentapi_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicledependentapi",
            name="pitb_api_code",
            field=models.TextField(max_length=200, null=True),
        ),
    ]
