# Generated by Django 5.1.7 on 2025-05-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppVehicle", "0029_vehicledependentapi_pitb_api_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackerrawdata",
            name="push_status",
            field=models.TextField(max_length=200, null=True),
        ),
    ]
