# Generated by Django 5.1.7 on 2025-05-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppVehicle", "0030_trackerrawdata_push_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackerrawdata",
            name="sync_code",
            field=models.TextField(max_length=200, null=True),
        ),
    ]
