# Generated by Django 5.1.7 on 2025-06-17 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppVehicle", "0031_trackerrawdata_sync_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiclelivemonitor",
            name="vehicle_code",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="live_monitor",
                to="AppVehicle.vehicledata",
                to_field="vehicle_code",
            ),
        ),
    ]
