# Generated by Django 5.1.7 on 2025-07-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppVehicle", "0033_complaint"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleThreshold",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("vehicle_type", models.CharField(max_length=100, null=True)),
                ("distance", models.FloatField(null=True)),
                ("working_hours", models.FloatField(null=True)),
                (
                    "ignition_status",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")],
                        default="No",
                        max_length=3,
                        null=True,
                    ),
                ),
                ("description", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.CharField(default="admin", max_length=200, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.CharField(default="admin", max_length=200, null=True),
                ),
            ],
            options={
                "db_table": "tbl_vehicle_threshold",
            },
        ),
    ]
