# Generated by Django 5.1.7 on 2025-07-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppVehicle", "0034_vehiclethreshold"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehiclethreshold",
            name="status",
            field=models.CharField(
                choices=[("Pending", "Pending"), ("Completed", "Completed")],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
