# Generated by Django 5.1.7 on 2025-07-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppVehicle", "0035_vehiclethreshold_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicleschedulegprsapi",
            name="distance",
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name="vehicleschedulegprsapi",
            name="ignition_status",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="No",
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vehicleschedulegprsapi",
            name="working_hours",
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
