# Generated by Django 5.1.7 on 2025-07-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppVehicle", "0036_vehicleschedulegprsapi_distance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicleschedulegprsapi",
            name="threshold",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="No",
                max_length=3,
                null=True,
            ),
        ),
    ]
