# Generated by Django 5.1.7 on 2025-07-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppVehicle", "0037_vehicleschedulegprsapi_threshold"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehiclethreshold",
            name="min_distance",
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="vehiclethreshold",
            name="distance",
            field=models.FloatField(default=0, null=True),
        ),
    ]
