# Generated by Django 5.1.7 on 2025-07-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppVehicle", "0038_vehiclethreshold_min_distance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicledata",
            name="date_installed",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicledata",
            name="engin_temp",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicledata",
            name="engine_hours",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicledata",
            name="ext_bat_voltage",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicledata",
            name="fuel_consumed",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicledata",
            name="fuel_level",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicledata",
            name="installation_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicledata",
            name="int_bat_voltage",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicledata",
            name="mileage_cur_value",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicledata",
            name="veh_status_chg_sec",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicledata",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
