# Generated by Django 5.1.7 on 2025-07-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "AppVehicle",
            "0039_vehicledata_date_installed_vehicledata_engin_temp_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="driverdata",
            name="driver_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="driverdata",
            name="driver_cnic",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="driverdata",
            name="driver_joining_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="driverdata",
            name="driver_license_expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="driverdata",
            name="driver_license_no",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="driverdata",
            name="driver_mobile",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
