# Generated by Django 5.1.7 on 2025-07-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "AppVehicle",
            "0040_driverdata_driver_address_driverdata_driver_cnic_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="trackerrawdata",
            name="engin_temp",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trackerrawdata",
            name="engine_hours",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trackerrawdata",
            name="ext_bat_voltage",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trackerrawdata",
            name="fuel_consumed",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trackerrawdata",
            name="fuel_level",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trackerrawdata",
            name="geo_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="trackerrawdata",
            name="gps_satelite",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trackerrawdata",
            name="gsm_signal",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trackerrawdata",
            name="int_bat_voltage",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trackerrawdata",
            name="location",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="trackerrawdata",
            name="location_a",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="trackerrawdata",
            name="mileage_cur_value",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trackerrawdata",
            name="minutes_diff",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trackerrawdata",
            name="rpm",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
