# Generated by Django 5.1.7 on 2025-07-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppVehicle", "0041_trackerrawdata_engin_temp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehiclelivemonitor",
            name="ext_bat_voltage",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehiclelivemonitor",
            name="gsm_signal",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehiclelivemonitor",
            name="int_bat_voltage",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
