# Generated by Django 5.1.7 on 2025-07-12 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppVehicle", "0042_vehiclelivemonitor_ext_bat_voltage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_no",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("customer_id", models.CharField(blank=True, max_length=50, null=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "father_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("dob", models.DateTimeField(blank=True, null=True)),
                ("str_dob", models.CharField(blank=True, max_length=50, null=True)),
                ("cnic_no", models.CharField(blank=True, max_length=20, null=True)),
                ("cell_phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "emergency_ph1",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "emergency_cel1",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("ins_co", models.CharField(blank=True, max_length=100, null=True)),
                ("region", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "group_title",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("ins_br", models.CharField(blank=True, max_length=100, null=True)),
                ("ins_agn", models.CharField(blank=True, max_length=100, null=True)),
                ("ins_sd", models.DateTimeField(blank=True, null=True)),
                ("ins_ed", models.DateTimeField(blank=True, null=True)),
                ("str_ins_sd", models.CharField(blank=True, max_length=50, null=True)),
                ("str_ins_ed", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "sale_type_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.CharField(default="admin", max_length=200, null=True),
                ),
            ],
            options={
                "db_table": "tbl_customer_data",
            },
        ),
        migrations.CreateModel(
            name="TelecomData",
            fields=[
                ("telecom_id", models.AutoField(primary_key=True, serialize=False)),
                ("sim_no", models.CharField(max_length=50, unique=True)),
                ("gsm_co", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "tbl_telecom_data",
            },
        ),
        migrations.CreateModel(
            name="TrackerCompany",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "company_code",
                    models.CharField(max_length=200, null=True, unique=True),
                ),
                ("company_name", models.CharField(max_length=100, null=True)),
                ("uan_no", models.CharField(max_length=200, null=True)),
                ("ntn_no", models.CharField(max_length=200, null=True)),
                ("strn_no", models.CharField(max_length=200, null=True)),
                ("address", models.CharField(max_length=200, null=True)),
                ("mobile", models.CharField(max_length=200, null=True)),
                ("area", models.CharField(max_length=100, null=True)),
                ("city", models.CharField(max_length=200, null=True)),
                ("state", models.CharField(blank=True, max_length=200, null=True)),
                ("status", models.CharField(max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(max_length=200, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("updated_by", models.CharField(max_length=200, null=True)),
            ],
            options={
                "db_table": "tbl_company",
            },
        ),
        migrations.CreateModel(
            name="TrackerData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("terminal_code", models.CharField(max_length=100, unique=True)),
                ("tracker_company_code", models.CharField(max_length=100)),
                ("modal_no", models.CharField(blank=True, max_length=100, null=True)),
                ("minutes_diff", models.IntegerField(blank=True, null=True)),
                ("ins_co", models.CharField(blank=True, max_length=100, null=True)),
                ("region", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "group_title",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("gps_satelite", models.IntegerField(blank=True, null=True)),
                ("gsm_signal", models.FloatField(blank=True, null=True)),
                (
                    "sale_type_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Blocked", "Blocked")],
                        default="Active",
                        max_length=10,
                    ),
                ),
                (
                    "terminal_type",
                    models.CharField(
                        choices=[("installed", "Installed"), ("advanced", "Advanced")],
                        max_length=10,
                    ),
                ),
                ("reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vehicle_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppVehicle.vehicledata",
                        to_field="vehicle_code",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_tracker_data",
            },
        ),
        migrations.CreateModel(
            name="TerminalRawData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppVehicle.telecomdata",
                    ),
                ),
                (
                    "terminal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_data",
                        to="AppVehicle.trackerdata",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_terminal_raw_data",
            },
        ),
        migrations.CreateModel(
            name="VehicleTerminalPairing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("installation_date", models.DateField(auto_now_add=True)),
                ("testing_time_from", models.TimeField(blank=True, null=True)),
                ("testing_time_to", models.TimeField(blank=True, null=True)),
                ("meter_reading", models.FloatField(null=True)),
                ("install_type", models.CharField(max_length=150, null=True)),
                ("location", models.CharField(max_length=200, null=True)),
                ("remarks", models.TextField(null=True)),
                ("region", models.CharField(max_length=200, null=True)),
                ("technician_name", models.CharField(max_length=150, null=True)),
                ("installation_place", models.CharField(max_length=200, null=True)),
                (
                    "old_customer_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "old_vehicle_pitb_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "old_vehicle_register_no",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.CharField(default="admin", max_length=200, null=True),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicle_pairings",
                        to="AppVehicle.customer",
                    ),
                ),
                (
                    "new_terminal",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="new_terminal",
                        to="AppVehicle.trackerdata",
                        to_field="terminal_code",
                    ),
                ),
                (
                    "old_terminal",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="old_terminal",
                        to="AppVehicle.trackerdata",
                        to_field="terminal_code",
                    ),
                ),
                (
                    "vehicle_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppVehicle.vehicledata",
                        to_field="vehicle_code",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_vehicle_terminal_pairing",
            },
        ),
    ]
