# Generated by Django 5.1.7 on 2025-07-14 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppVehicle", "0043_customer_telecomdata_trackercompany_trackerdata_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackerTelecomData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(default="Active", max_length=20)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("changed_by", models.CharField(max_length=100)),
                (
                    "sim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppVehicle.telecomdata",
                    ),
                ),
                (
                    "terminal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_data",
                        to="AppVehicle.trackerdata",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_tracker_telecom_data",
            },
        ),
        migrations.DeleteModel(
            name="TerminalRawData",
        ),
    ]
