# Generated by Django 5.1.7 on 2025-07-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppVehicle", "0044_trackertelecomdata_delete_terminalrawdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackerdata",
            name="created_by",
            field=models.CharField(
                blank=True, default="admin", max_length=200, null=True
            ),
        ),
    ]
