# Generated by Django 5.1.7 on 2025-07-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppVehicle", "0045_trackerdata_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="updated_by",
            field=models.CharField(
                blank=True, default="admin", max_length=200, null=True
            ),
        ),
    ]
