# Generated by Django 5.1.7 on 2025-07-17 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppVehicle", "0046_customer_updated_at_customer_updated_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="telecomdata",
            name="created_by",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="telecomdata",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="telecomdata",
            name="updated_by",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="trackerdata",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trackerdata",
            name="updated_by",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="trackertelecomdata",
            name="assigned_by",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
