# Generated by Django 5.1.7 on 2025-07-26 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppVehicle", "0047_telecomdata_created_by_telecomdata_updated_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackerDataLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(auto_now_add=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "db_table": "tbl_tracker_data_log",
            },
        ),
        migrations.RemoveField(
            model_name="trackerdata",
            name="vehicle_code",
        ),
        migrations.AddField(
            model_name="telecomdata",
            name="status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Blocked", "Blocked")],
                default="Active",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="TrackerVehicleData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Blocked", "Blocked")],
                        default="Active",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=200, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "terminal_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppVehicle.trackerdata",
                        to_field="terminal_code",
                    ),
                ),
                (
                    "vehicle_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppVehicle.vehicledata",
                        to_field="vehicle_code",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_tracker_vehicle_data",
            },
        ),
        migrations.CreateModel(
            name="TrackerVehicleLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_terminal_code", models.CharField(max_length=100)),
                ("new_terminal_code", models.CharField(max_length=100)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(auto_now_add=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "vehicle_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppVehicle.vehicledata",
                        to_field="vehicle_code",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_tracker_vehicle_log",
            },
        ),
    ]
