# Generated by Django 5.1.7 on 2025-07-26 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppVehicle", "0048_trackerdatalog_remove_trackerdata_vehicle_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trackertelecomdata",
            name="terminal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tracker_telecom_data",
                to="AppVehicle.trackervehicledata",
            ),
        ),
    ]
