# Generated by Django 5.1.7 on 2025-08-01 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppVehicle", "0049_alter_trackertelecomdata_terminal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="telecomdata",
            name="status",
        ),
        migrations.RemoveField(
            model_name="trackerdata",
            name="status",
        ),
        migrations.AddField(
            model_name="telecomdata",
            name="connected",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")], default="No", max_length=10
            ),
        ),
    ]
