# Generated by Django 5.1.7 on 2025-08-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "AppVehicle",
            "0050_remove_telecomdata_status_remove_trackerdata_status_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="trackerrawdata",
            old_name="geo_status",
            new_name="acc_status",
        ),
        migrations.RenameField(
            model_name="trackerrawdata",
            old_name="engin_temp",
            new_name="engine_temp",
        ),
        migrations.AddField(
            model_name="trackerrawdata",
            name="gis_geo_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="trackerrawdata",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trackerrawdata",
            name="updated_by",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
