# Generated by Django 5.1.7 on 2025-08-13 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppVehicle", "0051_rename_geo_status_trackerrawdata_acc_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OwnerData",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("owner_code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=200, null=True)),
                ("cnic", models.CharField(max_length=15, null=True, unique=True)),
                ("address", models.TextField(max_length=500, null=True)),
                ("phone_number", models.CharField(max_length=15, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Block", "Block")],
                        default="Active",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(max_length=200, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.CharField(max_length=200, null=True)),
            ],
            options={
                "db_table": "tbl_owner_data",
            },
        ),
        migrations.RenameField(
            model_name="driverdata",
            old_name="driver_name",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="driverdata",
            name="driver_address",
        ),
        migrations.RemoveField(
            model_name="driverdata",
            name="driver_cnic",
        ),
        migrations.RemoveField(
            model_name="driverdata",
            name="driver_joining_date",
        ),
        migrations.RemoveField(
            model_name="driverdata",
            name="driver_license_expiry_date",
        ),
        migrations.RemoveField(
            model_name="driverdata",
            name="driver_license_no",
        ),
        migrations.RemoveField(
            model_name="driverdata",
            name="driver_mobile",
        ),
        migrations.RemoveField(
            model_name="driverdata",
            name="status",
        ),
        migrations.RemoveField(
            model_name="vehicledriver",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="vehicledriver",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="vehicledriver",
            name="status",
        ),
        migrations.RemoveField(
            model_name="vehicledriver",
            name="veh_dr_code",
        ),
        migrations.AddField(
            model_name="driverdata",
            name="cnic",
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="driverdata",
            name="license_expiry",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="driverdata",
            name="license_no",
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="driverdata",
            name="phone_number",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="trackerrawdata",
            name="is_verified",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="vehicledata",
            name="ownership_status",
            field=models.CharField(
                choices=[("Owner", "Owner"), ("Rented", "Rented")],
                default="Owner",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="vehicledriver",
            name="end_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="vehicledriver",
            name="start_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="vehicledriver",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicledata",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="AppVehicle.ownerdata",
                to_field="owner_code",
            ),
        ),
    ]
