# Generated by Django 5.1.7 on 2025-08-23 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppVehicle", "0052_ownerdata_rename_driver_name_driverdata_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PITBVehicleIcon",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("vehicle_type", models.CharField(max_length=200, null=True)),
                (
                    "vehicle_icon",
                    models.ImageField(
                        blank=True, null=True, upload_to="pitb_vehicle_icons/"
                    ),
                ),
                (
                    "status",
                    models.CharField(default="Active", max_length=200, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(max_length=200, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "db_table": "tbl_pitb_vehicle_icon",
            },
        ),
        migrations.CreateModel(
            name="VehicleUsedFor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("vehicle_used_for", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(max_length=200, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.CharField(max_length=200, null=True)),
            ],
            options={
                "db_table": "tbl_vehicle_used_for",
            },
        ),
        migrations.AddField(
            model_name="vehicletype",
            name="vehicle_icon",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="AppVehicle.pitbvehicleicon",
            ),
        ),
        migrations.AddField(
            model_name="vehicletype",
            name="vehicle_used_for",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="AppVehicle.vehicleusedfor",
            ),
        ),
    ]
