# Generated by Django 5.1.7 on 2025-08-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppVehicle", "0053_pitbvehicleicon_vehicleusedfor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicledata",
            name="vtms_status",
            field=models.CharField(
                choices=[("Working", "Working"), ("Stop", "Stop")],
                default="Working",
                max_length=12,
            ),
        ),
    ]
