# Generated by Django 5.1.7 on 2025-08-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppVehicle", "0054_vehicledata_vtms_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicletype",
            name="vehicle_icon",
            field=models.ImageField(null=True, upload_to="VehicleIcon/"),
        ),
        migrations.AlterField(
            model_name="vehicletype",
            name="vehicle_used_for",
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name="PITBVehicleIcon",
        ),
        migrations.DeleteModel(
            name="VehicleUsedFor",
        ),
    ]
