# Generated by Django 5.1.7 on 2025-09-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppVehicle", "0055_alter_vehicletype_vehicle_icon_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicletype",
            name="vehicle_used_for",
        ),
        migrations.AddField(
            model_name="vehicledata",
            name="vehicle_used_for",
            field=models.TextField(null=True),
        ),
    ]
