# Generated by Django 5.1.7 on 2025-09-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppVehicle", "0056_remove_vehicletype_vehicle_used_for_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleUsedFor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "vehicle_use_code",
                    models.CharField(max_length=200, null=True, unique=True),
                ),
                ("vehicle_use_name", models.TextField(max_length=100, null=True)),
                ("description", models.TextField(max_length=200, null=True)),
                ("status", models.TextField(max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now=True, null=True)),
                ("created_by", models.CharField(max_length=200, null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("updated_by", models.CharField(max_length=200, null=True)),
            ],
            options={
                "db_table": "tbl_vehicle_use_for",
            },
        ),
        migrations.AddField(
            model_name="vehicletype",
            name="description",
            field=models.TextField(max_length=200, null=True),
        ),
    ]
