# Generated by Django 5.1.7 on 2025-09-04 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppVehicle", "0057_vehicleusedfor_vehicletype_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicledata",
            name="vehicle_used_for",
        ),
        migrations.AddField(
            model_name="vehicledata",
            name="vehicle_use_code",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="AppVehicle.vehicleusedfor",
                to_field="vehicle_use_code",
            ),
        ),
    ]
