# Generated by Django 5.1.7 on 2025-09-05 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppVehicle", "0058_remove_vehicledata_vehicle_used_for_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleDataLog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("before_data", models.JSONField(null=True)),
                ("after_data", models.JSONField(null=True)),
                ("created_at", models.DateTimeField(auto_now=True, null=True)),
                ("created_by", models.CharField(max_length=200, null=True)),
                (
                    "vehicle_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppVehicle.vehicledata",
                        to_field="vehicle_code",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_vehicle_data_logs",
            },
        ),
    ]
