# Generated by Django 5.1.7 on 2025-09-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppVehicle", "0059_vehicledatalog"),
    ]

    operations = [
        migrations.AddField(
            model_name="ownerdata",
            name="owner_type",
            field=models.CharField(
                choices=[("Self", "Self"), ("Vendor", "Vendor")],
                max_length=10,
                null=True,
            ),
        ),
    ]
