# Generated by Django 5.1.7 on 2025-09-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppVehicle", "0060_ownerdata_owner_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackerrawdata",
            name="working_hours",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
