# Generated by Django 5.1.7 on 2025-09-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppVehicle", "0061_trackerrawdata_working_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackerrawdata",
            name="threshold_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
