# Generated by Django 5.1.7 on 2025-04-30 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("AppVehicle", "0024_weighingtripdata"),
        ("DataLogs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="APITripData",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("before_weight", models.FloatField()),
                ("after_weight", models.FloatField()),
                ("time_in", models.DateTimeField()),
                ("time_out", models.DateTimeField()),
                ("before_picture", models.ImageField(upload_to="trip_pics/before/")),
                ("after_picture", models.ImageField(upload_to="trip_pics/after/")),
                (
                    "roof_before_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="trip_pics/roof_before/"
                    ),
                ),
                (
                    "roof_after_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="trip_pics/roof_after/"
                    ),
                ),
                ("uuid", models.CharField(blank=True, max_length=100, null=True)),
                ("slip_id", models.CharField(max_length=100, unique=True)),
                ("data_id", models.IntegerField(blank=True, null=True)),
                ("lat", models.FloatField()),
                ("long", models.FloatField()),
                ("site_name", models.CharField(max_length=255)),
                ("site_id", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now=True, null=True)),
                ("created_by", models.CharField(max_length=200, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("updated_by", models.CharField(max_length=200, null=True)),
                (
                    "gprs_raw_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppVehicle.trackerrawdata",
                        to_field="gprs_raw_code",
                    ),
                ),
                (
                    "tms_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DataLogs.apitransmissiondata",
                        to_field="tms_code",
                    ),
                ),
                (
                    "vehicle_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppVehicle.vehicledata",
                        to_field="vehicle_code",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_api_trip_data",
            },
        ),
    ]
