# Generated by Django 5.1.7 on 2025-05-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("VTCS", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apitripdata",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="apitripdata",
            name="response_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="apitripdata",
            name="response_status",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
