# Generated by Django 5.1.7 on 2025-05-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("VTCS", "0002_apitripdata_remarks_apitripdata_response_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apitripdata",
            name="trip_date",
            field=models.DateField(null=True),
        ),
    ]
