# Generated by Django 5.1.7 on 2025-05-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("VTCS", "0004_alter_apitripdata_slip_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apitripdata",
            name="slip_id",
            field=models.IntegerField(unique=True),
        ),
    ]
