# Generated by Django 5.1.7 on 2025-05-12 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("VTCS", "0005_alter_apitripdata_slip_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiTripDataLogs",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("current_response", models.TextField(blank=True, null=True)),
                ("hit_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trip_data_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trip_data_logs",
                        to="VTCS.apitripdata",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_api_trip_data_logs",
            },
        ),
    ]
