# Generated by Django 5.1.7 on 2025-05-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("VTCS", "0006_apitripdatalogs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apitripdata",
            name="after_picture",
            field=models.ImageField(default="", upload_to="VTCSTrip/after/"),
        ),
        migrations.AlterField(
            model_name="apitripdata",
            name="before_picture",
            field=models.ImageField(default="", upload_to="VTCSTrip/before/"),
        ),
        migrations.AlterField(
            model_name="apitripdata",
            name="roof_after_picture",
            field=models.ImageField(default="", upload_to="VTCSTrip/roof_after/"),
        ),
        migrations.AlterField(
            model_name="apitripdata",
            name="roof_before_picture",
            field=models.ImageField(default="", upload_to="VTCSTrip/roof_before/"),
        ),
    ]
