# Generated by Django 5.1.7 on 2025-05-16 05:15

import VTCS.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("VTCS", "0007_alter_apitripdata_after_picture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apitripdata",
            name="after_picture",
            field=models.ImageField(upload_to=VTCS.models.after_picture_path),
        ),
        migrations.AlterField(
            model_name="apitripdata",
            name="before_picture",
            field=models.ImageField(upload_to=VTCS.models.before_picture_path),
        ),
        migrations.AlterField(
            model_name="apitripdata",
            name="roof_after_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to=VTCS.models.roof_after_picture_path
            ),
        ),
        migrations.AlterField(
            model_name="apitripdata",
            name="roof_before_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to=VTCS.models.roof_before_picture_path
            ),
        ),
    ]
