# Generated by Django 5.1.4 on 2025-01-14 07:14

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TownBoundary",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("town_code", models.CharField(max_length=200, null=True, unique=True)),
                ("town_name", models.TextField(max_length=100, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("province", models.TextField(max_length=200, null=True)),
                ("shape_area", models.FloatField(max_length=200, null=True)),
                ("extent", models.TextField(max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(max_length=200, null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("updated_by", models.CharField(max_length=200, null=True)),
            ],
            options={
                "db_table": "tbl_town_boundary",
            },
        ),
        migrations.CreateModel(
            name="ZoneBoundary",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("zone_code", models.CharField(max_length=200, null=True, unique=True)),
                ("zone_name", models.TextField(max_length=100, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("shape_area", models.FloatField(max_length=200, null=True)),
                ("extent", models.TextField(max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(max_length=200, null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("updated_by", models.CharField(max_length=200, null=True)),
                (
                    "town_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppSetting.townboundary",
                        to_field="town_code",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_zone_boundary",
            },
        ),
        migrations.CreateModel(
            name="MCBoundary",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("mc_code", models.CharField(max_length=200, null=True, unique=True)),
                ("mc_name", models.TextField(max_length=100, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("shape_area", models.FloatField(max_length=200, null=True)),
                ("extent", models.TextField(max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(max_length=200, null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("updated_by", models.CharField(max_length=200, null=True)),
                (
                    "zone_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppSetting.zoneboundary",
                        to_field="zone_code",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_mc_boundary",
            },
        ),
    ]
