# Generated by Django 5.1.7 on 2025-04-10 17:53

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppSetting", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnionCouncil",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("uc_code", models.CharField(max_length=200, null=True, unique=True)),
                ("uc_name", models.TextField(max_length=100, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("shape_area", models.FloatField(max_length=200, null=True)),
                ("extent", models.TextField(max_length=200, null=True)),
                ("tehsil_name", models.TextField(max_length=100, null=True)),
                ("district_name", models.TextField(max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(max_length=200, null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("updated_by", models.CharField(max_length=200, null=True)),
                (
                    "town_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppSetting.townboundary",
                        to_field="town_code",
                    ),
                ),
                (
                    "zone_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppSetting.zoneboundary",
                        to_field="zone_code",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_union_council_boundary",
            },
        ),
    ]
