# Generated by Django 5.1.7 on 2025-04-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppSetting", "0002_unioncouncil"),
    ]

    operations = [
        migrations.AddField(
            model_name="unioncouncil",
            name="status",
            field=models.TextField(max_length=200, null=True),
        ),
    ]
