# Generated by Django 5.1.7 on 2025-04-22 18:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppSetting", "0003_unioncouncil_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="DivisionBoundary",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "division_code",
                    models.CharField(max_length=200, null=True, unique=True),
                ),
                ("division_name", models.TextField(max_length=100, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("province", models.TextField(max_length=200, null=True)),
                ("province_u", models.TextField(max_length=200, null=True)),
                ("shape_area", models.FloatField(max_length=200, null=True)),
                ("extent", models.TextField(max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(max_length=200, null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("updated_by", models.CharField(max_length=200, null=True)),
            ],
            options={
                "db_table": "tbl_division_boundary",
            },
        ),
    ]
