# Generated by Django 5.1.7 on 2025-04-22 19:00

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppSetting", "0007_landuseboundary"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdministrativeBoundary",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "admin_code",
                    models.CharField(max_length=200, null=True, unique=True),
                ),
                ("admin_name", models.TextField(max_length=100, null=True)),
                ("admin_type", models.TextField(max_length=200, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("extent", models.TextField(max_length=200, null=True)),
                ("status", models.TextField(max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(max_length=200, null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("updated_by", models.CharField(max_length=200, null=True)),
                (
                    "landuse_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppSetting.landuseboundary",
                        to_field="landuse_code",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_administrative_boundary",
            },
        ),
    ]
