# Generated by Django 5.1.7 on 2025-04-30 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("AppVehicle", "0024_weighingtripdata"),
        ("DataLogs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="APIVTMSData",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=200, null=True, unique=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("speed", models.FloatField(blank=True, null=True)),
                ("distance", models.FloatField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("vehicle_status", models.TextField(blank=True, null=True)),
                ("engine_status", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now=True, null=True)),
                ("created_by", models.CharField(max_length=200, null=True)),
                (
                    "gprs_raw_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppVehicle.trackerrawdata",
                        to_field="gprs_raw_code",
                    ),
                ),
                (
                    "tms_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DataLogs.apitransmissiondata",
                        to_field="tms_code",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_api_vtms_data",
            },
        ),
        migrations.CreateModel(
            name="APIVTMSStopPointBulk",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("stopped_minutes", models.FloatField(blank=True, null=True)),
                ("stopped_time", models.TimeField()),
                ("restart_time", models.TimeField()),
                ("lat", models.FloatField()),
                ("long", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now=True, null=True)),
                ("created_by", models.CharField(max_length=200, null=True)),
                (
                    "gprs_raw_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppVehicle.trackerrawdata",
                        to_field="gprs_raw_code",
                    ),
                ),
                (
                    "tms_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DataLogs.apitransmissiondata",
                        to_field="tms_code",
                    ),
                ),
                (
                    "vehicle_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppVehicle.vehicledata",
                        to_field="vehicle_code",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_api_vtms_stop_point_bulk",
            },
        ),
    ]
