# Generated by Django 5.1.7 on 2025-04-28 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("AppVehicle", "0021_vehicleschedulegprsapi_veh_sch_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="PITBApiData",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=200, null=True, unique=True)),
                ("name", models.TextField(max_length=100, null=True)),
                ("function_name", models.CharField(max_length=200, null=True)),
                (
                    "hit_type",
                    models.CharField(
                        choices=[("multiple", "multiple"), ("single", "single")],
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "active"), ("blocked", "blocked")],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True, null=True)),
                ("created_by", models.CharField(max_length=200, null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("updated_by", models.CharField(max_length=200, null=True)),
            ],
            options={
                "db_table": "tbl_pitb_api_data",
            },
        ),
        migrations.CreateModel(
            name="ApiTransmissionData",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("tms_code", models.CharField(max_length=200, null=True, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "active"), ("blocked", "blocked")],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("response_code", models.CharField(max_length=200, null=True)),
                (
                    "response_status",
                    models.CharField(
                        choices=[("completed", "completed"), ("rejected", "rejected")],
                        max_length=10,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now=True, null=True)),
                ("created_by", models.CharField(max_length=200, null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("updated_by", models.CharField(max_length=200, null=True)),
                (
                    "vehicle_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppVehicle.vehicledata",
                        to_field="vehicle_code",
                    ),
                ),
                (
                    "pitb_api_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Communication.pitbapidata",
                        to_field="code",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_api_transmission_data",
            },
        ),
    ]
