# Generated by Django 5.1.7 on 2025-04-28 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppVehicle", "0021_vehicleschedulegprsapi_veh_sch_date"),
        ("Communication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiVTMSData",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=200, null=True, unique=True)),
                ("latitude", models.FloatField(null=True)),
                ("longitude", models.FloatField(null=True)),
                ("speed", models.FloatField(blank=True, null=True)),
                ("distance", models.FloatField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("vehicle_status", models.TextField(blank=True, null=True)),
                ("engine_status", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now=True, null=True)),
                ("created_by", models.CharField(max_length=200, null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("updated_by", models.CharField(max_length=200, null=True)),
                (
                    "gprs_raw_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppVehicle.trackerrawdata",
                        to_field="gprs_raw_code",
                    ),
                ),
                (
                    "tms_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Communication.apitransmissiondata",
                        to_field="tms_code",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_api_vtms_data",
            },
        ),
    ]
