# Generated by Django 5.1.7 on 2025-04-30 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Communication", "0002_apivtmsdata"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apitransmissiondata",
            name="pitb_api_code",
        ),
        migrations.RemoveField(
            model_name="apitransmissiondata",
            name="vehicle_code",
        ),
        migrations.RemoveField(
            model_name="apivtmsdata",
            name="tms_code",
        ),
        migrations.RemoveField(
            model_name="apivtmsdata",
            name="gprs_raw_code",
        ),
        migrations.DeleteModel(
            name="PITBApiData",
        ),
        migrations.DeleteModel(
            name="ApiTransmissionData",
        ),
        migrations.DeleteModel(
            name="ApiVTMSData",
        ),
    ]
