# Generated by Django 5.1.4 on 2025-01-14 07:46

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("AppSetting", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContainerProcessType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "cont_proc_type_code",
                    models.CharField(max_length=200, null=True, unique=True),
                ),
                ("cont_proc_type_name", models.TextField(max_length=100, null=True)),
                ("duration_mint", models.TextField(max_length=200, null=True)),
                ("description", models.TextField(max_length=200, null=True)),
                ("status", models.TextField(max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now=True, null=True)),
                ("created_by", models.CharField(max_length=200, null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("updated_by", models.CharField(max_length=200, null=True)),
            ],
            options={
                "db_table": "tbl_container_process_type",
            },
        ),
        migrations.CreateModel(
            name="ContainerData",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("system_code", models.TextField(max_length=100, null=True)),
                (
                    "container_code",
                    models.CharField(max_length=200, null=True, unique=True),
                ),
                ("container_name", models.TextField(max_length=100, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("latitude", models.FloatField(null=True)),
                ("longitude", models.FloatField(null=True)),
                ("address", models.TextField(max_length=200, null=True)),
                ("area", models.TextField(max_length=100, null=True)),
                ("image", models.ImageField(null=True, upload_to="Asset/Container")),
                ("size", models.TextField(max_length=200, null=True)),
                ("install_year", models.TextField(null=True)),
                ("asset_condition", models.TextField(max_length=200, null=True)),
                ("category", models.TextField(max_length=200, null=True)),
                ("working_status", models.TextField(max_length=200, null=True)),
                ("plan_status", models.TextField(max_length=200, null=True)),
                ("status", models.TextField(max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now=True, null=True)),
                ("created_by", models.CharField(max_length=200, null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("updated_by", models.CharField(max_length=200, null=True)),
                (
                    "mc_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppSetting.mcboundary",
                        to_field="mc_code",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_container_data",
            },
        ),
        migrations.CreateModel(
            name="ContainerProcess",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "container_process_code",
                    models.CharField(max_length=200, null=True, unique=True),
                ),
                ("check_in", models.TextField(max_length=200, null=True)),
                ("check_out", models.TextField(max_length=200, null=True)),
                ("net_time_spent", models.TextField(max_length=200, null=True)),
                ("status", models.TextField(max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now=True, null=True)),
                ("created_by", models.CharField(max_length=200, null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("updated_by", models.CharField(max_length=200, null=True)),
                (
                    "container_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppAsset.containerdata",
                        to_field="container_code",
                    ),
                ),
                (
                    "cont_proc_type_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppAsset.containerprocesstype",
                        to_field="cont_proc_type_code",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_container_process",
            },
        ),
    ]
