# Generated by Django 5.1.4 on 2025-01-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppAsset", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="containerdata",
            name="install_year",
            field=models.DateField(null=True),
        ),
    ]
