# Generated by Django 5.1.4 on 2025-01-28 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppAsset", "0002_alter_containerdata_install_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetGroup",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "asset_group_code",
                    models.CharField(max_length=200, null=True, unique=True),
                ),
                ("asset_group_name", models.TextField(max_length=100, null=True)),
                ("description", models.TextField(max_length=200, null=True)),
                ("status", models.TextField(max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(max_length=200, null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("updated_by", models.CharField(max_length=200, null=True)),
            ],
            options={
                "db_table": "tbl_asset_group",
            },
        ),
        migrations.CreateModel(
            name="AssetType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "asset_code",
                    models.CharField(max_length=100, null=True, unique=True),
                ),
                ("asset_name", models.TextField(max_length=100, null=True)),
                ("description", models.TextField(max_length=200, null=True)),
                ("status", models.TextField(max_length=200, null=True)),
                ("model_table", models.TextField(max_length=200, null=True)),
                ("shape_type", models.TextField(max_length=100, null=True)),
                ("manual_code", models.TextField(max_length=100, null=True)),
                ("image", models.ImageField(null=True, upload_to="AssetType")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(max_length=200, null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("updated_by", models.CharField(max_length=200, null=True)),
                (
                    "asset_group_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppAsset.assetgroup",
                        to_field="asset_group_code",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_asset_type",
            },
        ),
    ]
