# Generated by Django 5.1.4 on 2025-01-28 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppAsset", "0003_assetgroup_assettype"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetGeoFence",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geofence_code",
                    models.CharField(max_length=100, null=True, unique=True),
                ),
                ("distance", models.IntegerField(null=True)),
                ("radius", models.IntegerField(null=True)),
                ("description", models.TextField(max_length=200, null=True)),
                ("status", models.TextField(max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(max_length=200, null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("updated_by", models.CharField(max_length=200, null=True)),
                (
                    "asset_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppAsset.assettype",
                        to_field="asset_code",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_asset_geo_fence",
            },
        ),
    ]
