# Generated by Django 5.1.4 on 2025-01-28 06:49

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppAsset", "0004_assetgeofence"),
        ("AppSetting", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DumpingSite",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=200, null=True, unique=True)),
                ("name", models.TextField(max_length=100, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("latitude", models.FloatField(null=True)),
                ("longitude", models.FloatField(null=True)),
                ("address", models.TextField(max_length=200, null=True)),
                ("area", models.TextField(max_length=100, null=True)),
                ("image", models.ImageField(null=True, upload_to="Asset/DumpingSite")),
                ("install_year", models.DateField(null=True)),
                ("condition", models.TextField(max_length=200, null=True)),
                ("working_status", models.TextField(max_length=200, null=True)),
                ("plan_status", models.TextField(max_length=200, null=True)),
                ("status", models.TextField(max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now=True, null=True)),
                ("created_by", models.CharField(max_length=200, null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("updated_by", models.CharField(max_length=200, null=True)),
                (
                    "mc_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppSetting.mcboundary",
                        to_field="mc_code",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_dumping_site",
            },
        ),
        migrations.CreateModel(
            name="FillingStation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=200, null=True, unique=True)),
                ("name", models.TextField(max_length=100, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("latitude", models.FloatField(null=True)),
                ("longitude", models.FloatField(null=True)),
                ("address", models.TextField(max_length=200, null=True)),
                ("area", models.TextField(max_length=100, null=True)),
                (
                    "image",
                    models.ImageField(null=True, upload_to="Asset/FillingStation"),
                ),
                ("install_year", models.DateField(null=True)),
                ("condition", models.TextField(max_length=200, null=True)),
                ("working_status", models.TextField(max_length=200, null=True)),
                ("plan_status", models.TextField(max_length=200, null=True)),
                ("status", models.TextField(max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now=True, null=True)),
                ("created_by", models.CharField(max_length=200, null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("updated_by", models.CharField(max_length=200, null=True)),
                (
                    "mc_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppSetting.mcboundary",
                        to_field="mc_code",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_filling_station",
            },
        ),
        migrations.CreateModel(
            name="LandfillSite",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=200, null=True, unique=True)),
                ("name", models.TextField(max_length=100, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("latitude", models.FloatField(null=True)),
                ("longitude", models.FloatField(null=True)),
                ("address", models.TextField(max_length=200, null=True)),
                ("area", models.TextField(max_length=100, null=True)),
                ("image", models.ImageField(null=True, upload_to="Asset/Landfill")),
                ("install_year", models.DateField(null=True)),
                ("condition", models.TextField(max_length=200, null=True)),
                ("working_status", models.TextField(max_length=200, null=True)),
                ("plan_status", models.TextField(max_length=200, null=True)),
                ("status", models.TextField(max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now=True, null=True)),
                ("created_by", models.CharField(max_length=200, null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("updated_by", models.CharField(max_length=200, null=True)),
                (
                    "mc_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppSetting.mcboundary",
                        to_field="mc_code",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_landfill_site",
            },
        ),
        migrations.CreateModel(
            name="ParkingSite",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=200, null=True, unique=True)),
                ("name", models.TextField(max_length=100, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("latitude", models.FloatField(null=True)),
                ("longitude", models.FloatField(null=True)),
                ("address", models.TextField(max_length=200, null=True)),
                ("area", models.TextField(max_length=100, null=True)),
                ("image", models.ImageField(null=True, upload_to="Asset/ParkingSite")),
                ("install_year", models.DateField(null=True)),
                ("condition", models.TextField(max_length=200, null=True)),
                ("working_status", models.TextField(max_length=200, null=True)),
                ("plan_status", models.TextField(max_length=200, null=True)),
                ("status", models.TextField(max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now=True, null=True)),
                ("created_by", models.CharField(max_length=200, null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("updated_by", models.CharField(max_length=200, null=True)),
                (
                    "mc_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppSetting.mcboundary",
                        to_field="mc_code",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_parking_site",
            },
        ),
        migrations.CreateModel(
            name="TransferStation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=200, null=True, unique=True)),
                ("name", models.TextField(max_length=100, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("latitude", models.FloatField(null=True)),
                ("longitude", models.FloatField(null=True)),
                ("address", models.TextField(max_length=200, null=True)),
                ("area", models.TextField(max_length=100, null=True)),
                (
                    "image",
                    models.ImageField(null=True, upload_to="Asset/TransferStation"),
                ),
                ("install_year", models.DateField(null=True)),
                ("condition", models.TextField(max_length=200, null=True)),
                ("working_status", models.TextField(max_length=200, null=True)),
                ("plan_status", models.TextField(max_length=200, null=True)),
                ("status", models.TextField(max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now=True, null=True)),
                ("created_by", models.CharField(max_length=200, null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("updated_by", models.CharField(max_length=200, null=True)),
                (
                    "mc_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppSetting.mcboundary",
                        to_field="mc_code",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_transfer_station",
            },
        ),
        migrations.CreateModel(
            name="Workshop",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=200, null=True, unique=True)),
                ("name", models.TextField(max_length=100, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("latitude", models.FloatField(null=True)),
                ("longitude", models.FloatField(null=True)),
                ("address", models.TextField(max_length=200, null=True)),
                ("area", models.TextField(max_length=100, null=True)),
                ("image", models.ImageField(null=True, upload_to="Asset/ParkingSite")),
                ("install_year", models.DateField(null=True)),
                ("condition", models.TextField(max_length=200, null=True)),
                ("working_status", models.TextField(max_length=200, null=True)),
                ("plan_status", models.TextField(max_length=200, null=True)),
                ("status", models.TextField(max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now=True, null=True)),
                ("created_by", models.CharField(max_length=200, null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("updated_by", models.CharField(max_length=200, null=True)),
                (
                    "mc_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppSetting.mcboundary",
                        to_field="mc_code",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_workshop",
            },
        ),
    ]
