# Generated by Django 5.1.4 on 2025-02-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "AppAsset",
            "0005_dumpingsite_fillingstation_landfillsite_parkingsite_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="assetgeofence",
            name="model_table",
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="assetgeofence",
            name="shape_type",
            field=models.TextField(max_length=100, null=True),
        ),
    ]
