# Generated by Django 5.1.4 on 2025-02-26 11:49

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AppAsset", "0006_assetgeofence_model_table_assetgeofence_shape_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetgeofence",
            name="geom",
            field=django.contrib.gis.db.models.fields.GeometryField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
