# Generated by Django 5.1.4 on 2025-02-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppAsset", "0007_assetgeofence_geom"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetgeofence",
            name="feature_code",
            field=models.TextField(max_length=100, null=True),
        ),
    ]
