# Generated by Django 5.1.4 on 2025-02-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppAsset", "0008_assetgeofence_feature_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="containerprocess",
            name="vehicle_code_id",
            field=models.TextField(max_length=200, null=True),
        ),
    ]
