# Generated by Django 5.1.4 on 2025-03-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppAsset", "0009_containerprocess_vehicle_code_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="containerprocess",
            name="created_at",
            field=models.DateTimeField(null=True),
        ),
    ]
