# Generated by Django 5.1.4 on 2025-03-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppAsset", "0010_alter_containerprocess_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContainerType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "container_type_code",
                    models.CharField(max_length=200, null=True, unique=True),
                ),
                ("container_type_name", models.TextField(max_length=100, null=True)),
                ("status", models.TextField(max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now=True, null=True)),
                ("created_by", models.CharField(max_length=200, null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("updated_by", models.CharField(max_length=200, null=True)),
            ],
            options={
                "db_table": "tbl_container_type",
            },
        ),
    ]
