# Generated by Django 5.1.7 on 2025-04-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppAsset", "0012_dumpingcoverage"),
    ]

    operations = [
        migrations.AddField(
            model_name="containerdata",
            name="repeat_geom",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="containerdata",
            name="repeat_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="containerdata",
            name="serial_geom",
            field=models.IntegerField(null=True),
        ),
    ]
