# Generated by Django 5.1.7 on 2025-04-23 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppAsset", "0013_containerdata_repeat_geom_containerdata_repeat_id_and_more"),
        ("AppSetting", "0008_administrativeboundary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="containerdata",
            name="mc_code",
        ),
        migrations.AddField(
            model_name="containerdata",
            name="admin_code",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="AppSetting.administrativeboundary",
                to_field="admin_code",
            ),
        ),
    ]
