# Generated by Django 5.1.7 on 2025-04-23 11:44

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppAsset", "0015_drumdata"),
        ("AppSetting", "0008_administrativeboundary"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionSite",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("tcp_code", models.CharField(max_length=200, null=True, unique=True)),
                ("tcp_name", models.TextField(max_length=100, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("latitude", models.FloatField(null=True)),
                ("longitude", models.FloatField(null=True)),
                ("address", models.TextField(max_length=200, null=True)),
                ("area", models.TextField(max_length=100, null=True)),
                ("image", models.ImageField(null=True, upload_to="Asset/TCP")),
                ("install_year", models.DateField(null=True)),
                ("condition", models.TextField(max_length=200, null=True)),
                ("working_status", models.TextField(max_length=200, null=True)),
                ("plan_status", models.TextField(max_length=200, null=True)),
                ("status", models.TextField(max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now=True, null=True)),
                ("created_by", models.CharField(max_length=200, null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("updated_by", models.CharField(max_length=200, null=True)),
                (
                    "admin_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppSetting.administrativeboundary",
                        to_field="admin_code",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_collection_site",
            },
        ),
    ]
