# Generated by Django 5.1.7 on 2025-04-30 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PITBApiData",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "active"), ("blocked", "blocked")],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField()),
                ("function_name", models.CharField(max_length=100)),
                (
                    "hit_type",
                    models.CharField(
                        choices=[("multiple", "multiple"), ("single", "single")],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(max_length=100)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "tbl_pitb_api_data",
            },
        ),
    ]
