# Generated by Django 5.1.7 on 2025-05-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PITB_API_DATA", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pitbapidata",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
