# Generated by Django 5.1.7 on 2025-05-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PITB_API_DATA", "0002_alter_pitbapidata_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pitbapidata",
            name="hit_type",
            field=models.CharField(
                choices=[("multiple", "multiple"), ("single", "single")],
                max_length=10,
                null=True,
            ),
        ),
    ]
