# Generated by Django 5.1.7 on 2025-05-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PITB_API_DATA", "0003_alter_pitbapidata_hit_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pitbapidata",
            name="created_by",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="pitbapidata",
            name="function_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="pitbapidata",
            name="updated_by",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
