# Generated by Django 5.1.7 on 2025-07-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PITB_API_DATA", "0004_alter_pitbapidata_created_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PITBApiBulkVTMSLog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("method", models.CharField(max_length=100)),
                ("push_body", models.TextField(null=True)),
                ("push_date", models.DateField(auto_now_add=True)),
                ("push_time", models.TimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(max_length=100, null=True)),
            ],
            options={
                "db_table": "tbl_pitb_api_bulk_vtms_log",
            },
        ),
    ]
