# Generated by Django 5.1.7 on 2025-04-30 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("AppVehicle", "0024_weighingtripdata"),
        ("PITB_API_DATA", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="APITransmissionData",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("tms_code", models.CharField(max_length=10, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "active"), ("blocked", "blocked")],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("response_code", models.CharField(max_length=100)),
                (
                    "response_status",
                    models.CharField(
                        choices=[("completed", "completed"), ("rejected", "rejected")],
                        max_length=10,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(max_length=100)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.CharField(max_length=100)),
                (
                    "pitb_api_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PITB_API_DATA.pitbapidata",
                        to_field="code",
                    ),
                ),
                (
                    "vehicle_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppVehicle.vehicledata",
                        to_field="vehicle_code",
                    ),
                ),
            ],
        ),
    ]
