# Generated by Django 5.1.4 on 2025-01-21 07:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RouteNetwork",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "route_code",
                    models.CharField(max_length=200, null=True, unique=True),
                ),
                ("route_name", models.TextField(max_length=100, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("latitude", models.FloatField(null=True)),
                ("longitude", models.FloatField(null=True)),
                ("address", models.TextField(max_length=200, null=True)),
                ("area", models.TextField(max_length=100, null=True)),
                ("type", models.TextField(max_length=200, null=True)),
                ("row", models.TextField(max_length=200, null=True)),
                ("length", models.TextField(max_length=200, null=True)),
                ("speed_limit", models.TextField(max_length=200, null=True)),
                ("category", models.TextField(max_length=200, null=True)),
                ("working_status", models.TextField(max_length=200, null=True)),
                ("plan_status", models.TextField(max_length=200, null=True)),
                ("status", models.TextField(max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now=True, null=True)),
                ("created_by", models.CharField(max_length=200, null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("updated_by", models.CharField(max_length=200, null=True)),
            ],
            options={
                "db_table": "tbl_route_network",
            },
        ),
    ]
