# Generated by Django 5.1.4 on 2025-01-21 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppAsset", "0002_alter_containerdata_install_year"),
        ("AppRoute", "0001_initial"),
        ("AppSetting", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RouteNetworkSchedule",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "route_sche_code",
                    models.CharField(max_length=200, null=True, unique=True),
                ),
                ("sche_group_code", models.TextField(max_length=200, null=True)),
                ("sche_group_name", models.TextField(max_length=200, null=True)),
                ("status", models.TextField(max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now=True, null=True)),
                ("created_by", models.CharField(max_length=200, null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("updated_by", models.CharField(max_length=200, null=True)),
                (
                    "mc_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppSetting.mcboundary",
                        to_field="mc_code",
                    ),
                ),
                (
                    "route_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppRoute.routenetwork",
                        to_field="route_code",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_route_network_schedule",
            },
        ),
        migrations.CreateModel(
            name="RouteContainer",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "route_cont_code",
                    models.CharField(max_length=200, null=True, unique=True),
                ),
                ("status", models.TextField(max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now=True, null=True)),
                ("created_by", models.CharField(max_length=200, null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("updated_by", models.CharField(max_length=200, null=True)),
                (
                    "container_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppAsset.containerdata",
                        to_field="container_code",
                    ),
                ),
                (
                    "route_sche_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppRoute.routenetworkschedule",
                        to_field="route_sche_code",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_route_container",
            },
        ),
    ]
