# Generated by Django 5.1.4 on 2025-02-06 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AppRoute", "0002_routenetworkschedule_routecontainer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="routenetwork",
            old_name="route_code",
            new_name="route_line_code",
        ),
        migrations.RenameField(
            model_name="routenetwork",
            old_name="route_name",
            new_name="route_line_name",
        ),
        migrations.RemoveField(
            model_name="routenetworkschedule",
            name="route_code",
        ),
    ]
