# Generated by Django 5.1.4 on 2025-02-06 07:58

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppRoute", "0003_rename_route_code_routenetwork_route_line_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RouteNetworkBoundary",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "route_code",
                    models.CharField(max_length=200, null=True, unique=True),
                ),
                ("route_name", models.TextField(max_length=100, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("address", models.TextField(max_length=200, null=True)),
                ("area", models.TextField(max_length=100, null=True)),
                ("upload_type", models.TextField(max_length=200, null=True)),
                ("row", models.TextField(max_length=200, null=True)),
                ("length", models.TextField(max_length=200, null=True)),
                ("speed_limit", models.TextField(max_length=200, null=True)),
                ("category", models.TextField(max_length=200, null=True)),
                ("working_status", models.TextField(max_length=200, null=True)),
                ("plan_status", models.TextField(max_length=200, null=True)),
                ("status", models.TextField(max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now=True, null=True)),
                ("created_by", models.CharField(max_length=200, null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("updated_by", models.CharField(max_length=200, null=True)),
                (
                    "route_line_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppRoute.routenetwork",
                        to_field="route_line_code",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_route_network_boundary",
            },
        ),
        migrations.AddField(
            model_name="routenetworkschedule",
            name="route_code",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="AppRoute.routenetworkboundary",
                to_field="route_code",
            ),
        ),
    ]
