# Generated by Django 5.1.4 on 2025-02-06 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AppRoute", "0004_routenetworkboundary_routenetworkschedule_route_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="routenetwork",
            old_name="row",
            new_name="row_m",
        ),
        migrations.RenameField(
            model_name="routenetworkboundary",
            old_name="row",
            new_name="row_m",
        ),
    ]
